[package]
name = "solana-devtools-tx"
version = "0.2.0"
edition = "2021"

[dependencies]
anchor-client = "0.26.0"
serde_json = "1.0.81"
serde = "1.0.140"
solana-sdk = "1.14.11"
thiserror = "1.0.37"
bincode = "1.3.3"

[dev-dependencies]
spl-memo = "3.0.1"
